### ISSUE TITLE
Does it work with Sendy latest version (v2.1.2)?

### ISSUE THREAD

**Issue by rhbkweb** [amargautam/sendy-mailgun#2]
Hi,

1- Does your Mailgun integration work with the latest Sendy version (v2.1.2)?

2- If yes, are you available for hire in order to make this integration on my current Sendy installation. If yes, we can talk in private about details and price.

Thanks

**Comment by amargautam** [comment]
No it doesn't. I started coding and I never got time to complete it. I will give it a shot again and see if I can. Or else will delete this project. Sorry about the confusion.

If I am able to complete it, the code will be open source. You will be able to integrate it yourself. If still not, I can always do it for you.
